import React from 'react';
import ReactMarkdown from 'react-markdown';
import { FileText, Search } from 'lucide-react';
import { FinanceProfile } from '../../services/financeEngine';

interface FinancialPlanViewProps {
  profile: FinanceProfile;
  reportData: any;
}

export const FinancialPlanView: React.FC<FinancialPlanViewProps> = ({ profile, reportData }) => {
  if (!reportData) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-center opacity-50 bg-[#0F172A] rounded-xl border border-white/10 h-full p-8">
        <Search className="w-16 h-16 text-slate-600 mb-4" />
        <h2 className="text-xl font-medium text-slate-400 mb-2">Analysis Pending</h2>
        <p className="text-sm text-slate-500 max-w-sm">
          Run the AI analysis to generate a comprehensive financial plan for {profile.name}.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-[#0F172A] rounded-xl border border-white/10 overflow-hidden shadow-2xl">
      <div className="bg-[#1E293B] px-5 py-4 border-b border-white/5 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-emerald-500/20 p-2 rounded-lg">
            <FileText className="w-5 h-5 text-emerald-400" />
          </div>
          <div>
            <h2 className="font-semibold text-slate-200">Raw Financial Plan</h2>
            <p className="text-xs text-slate-400">Generated by Orchestrator Agent</p>
          </div>
        </div>
      </div>
      
      <div className="flex-1 overflow-y-auto p-6 prose prose-invert prose-emerald max-w-none text-sm">
        <ReactMarkdown>{reportData.rawPlan}</ReactMarkdown>
      </div>
    </div>
  );
};
