import { getAIInstance, getOrchestratorAI, withRetry } from './gemini';
import { GEMINI_MODELS } from '../config/constants';

export interface FinanceProfile {
  name: string;
  age: number;
  netWorth: number;
  monthlyIncome: number;
  monthlyExpenses: number;
  riskAppetite: 'Beginner' | 'Moderate' | 'Aggressive';
  goals: string[];
  pastTrends: string;
}

export const generateRawClientData = (): string => {
  const jobs = ["Software Engineer", "Doctor", "Small Business Owner", "Teacher", "Investment Banker"];
  const job = jobs[Math.floor(Math.random() * jobs.length)];
  const age = Math.floor(Math.random() * 40) + 25;
  const baseSalary = Math.floor(Math.random() * 150000) + 50000;
  const savings = Math.floor(Math.random() * 500000) + 10000;
  const investments = Math.floor(Math.random() * 1000000);
  
  return `Client is a ${age}-year-old ${job}. They make roughly $${baseSalary} per year. They have $${savings} in savings and $${investments} in various investments like index funds and some stocks. They spend about 60% of their monthly income on living expenses. They want to buy a house in 5 years and retire at 60. They have panicked in past market crashes and sold off stocks, indicating they might be risk-averse, though they claim to want high growth.`;
};

// ── Profile Engine → GROQ (fast, structured JSON) ─────────────────────────
export const computeProfileFromData = async (rawData: string, onRetry?: (msg: string) => void): Promise<FinanceProfile> => {
  const prompt = `You are the Profile Engine. Extract and compute a structured financial profile from the following raw client data.
  
  RAW DATA:
  ${rawData}
  
  Compute the Net Worth (savings + investments + other assets), Monthly Income (annual / 12), and Monthly Expenses. Determine their true Risk Appetite (Beginner, Moderate, Aggressive) based on their behavior, not just what they claim.
  
  Return ONLY valid JSON matching this schema:
  {
    "name": "String",
    "age": Number,
    "netWorth": Number,
    "monthlyIncome": Number,
    "monthlyExpenses": Number,
    "riskAppetite": "Beginner" | "Moderate" | "Aggressive",
    "goals": ["Goal1", "Goal2"],
    "pastTrends": "Brief summary of past financial behavior"
  }
  Do not include markdown blocks, just the JSON string.`;

  const response = await withRetry(() => getOrchestratorAI().models.generateContent({
    model: GEMINI_MODELS.DEFAULT,
    contents: prompt
  }), onRetry);
  
  const text = response.text || '{}';
  const cleanJson = text.replace(/```json/g, '').replace(/```/g, '').trim();
  return JSON.parse(cleanJson);
};

// ── Orchestrator → GOOGLE KEY #2 (best reasoning for full financial plan) ─────────
export const orchestrateFinancePlan = async (profile: FinanceProfile, selectedShocks: string[] = [], onRetry?: (msg: string) => void): Promise<string> => {
  const ai = getOrchestratorAI();
  const shockText = selectedShocks.length > 0 ? `They are also facing these unexpected shock events: ${selectedShocks.join(', ')}.` : '';
  const prompt = `You are the Orchestrator (Lead Financial Strategist).
  
  Client Profile:
  Name: ${profile.name} (Age ${profile.age})
  Net Worth: $${profile.netWorth}
  Monthly Income: $${profile.monthlyIncome}
  Monthly Expenses: $${profile.monthlyExpenses}
  Risk Appetite: ${profile.riskAppetite}
  Goals: ${profile.goals.join(', ')}
  Past Trends: ${profile.pastTrends}
  ${shockText}
  
  Generate a comprehensive, expert-level financial plan (Markdown format). Include exact numeric allocations for savings, emergency funds, and investments based on their risk appetite. If there are shocks, explicitly address how the plan mitigates them.`;

  const response = await withRetry(() => ai.models.generateContent({
    model: GEMINI_MODELS.DEFAULT,
    contents: prompt
  }), onRetry);
  
  return response.text || 'Failed to generate plan.';
};

// ── Explainer → GROQ (summarisation, very fast) ───────────────────────────
export const generateExplanation = async (rawPlan: string, onRetry?: (msg: string) => void): Promise<string> => {
  const prompt = `You are the Explainer (Client-facing AI).
  
  Here is a complex financial plan generated by the Orchestrator:
  ${rawPlan}
  
  Translate this plan into a simple, easy-to-understand summary for the client. Use bullet points and clear, encouraging language. Remove complex jargon. (Markdown format)`;

  const response = await withRetry(() => getOrchestratorAI().models.generateContent({
    model: GEMINI_MODELS.DEFAULT,
    contents: prompt
  }), onRetry);
  return response.text || 'Explanation failed to generate.';
};

// ── Verifier → GROQ (JSON structured output) ──────────────────────────────
export const verifyNumbers = async (rawPlan: string, explanation: string, onRetry?: (msg: string) => void): Promise<{ verified: boolean; message: string; data: any }> => {
  const prompt = `You are the Verifier (Auditor AI).
  
  Raw Plan:
  ${rawPlan}
  
  Explanation provided to client:
  ${explanation}
  
  Task:
  1. Audit the numbers to ensure they match mathematically (e.g. percentages add up, allocations do not exceed income).
  2. Ensure the explanation does not hallucinate facts not present in the Raw Plan.
  
  Return ONLY valid JSON matching this schema:
  {
    "verified": boolean,
    "message": "String explaining the audit result",
    "data": { "issuesFound": number }
  }`;

  const response = await withRetry(() => getOrchestratorAI().models.generateContent({
    model: GEMINI_MODELS.DEFAULT,
    contents: prompt
  }), onRetry);
  
  const text = response.text || '{}';
  const cleanJson = text.replace(/```json/g, '').replace(/```/g, '').trim();
  return JSON.parse(cleanJson);
};

// ── Challenger → GROQ (critical reasoning, no quota pressure) ─────────────
export const generateChallenge = async (profile: FinanceProfile, rawPlan: string, onRetry?: (msg: string) => void): Promise<string> => {
  const prompt = `You are the Challenger (Devil's Advocate AI).
  
  Client Profile:
  Age: ${profile.age}, Net Worth: $${profile.netWorth}, Income: $${profile.monthlyIncome}, Risk: ${profile.riskAppetite}
  
  Proposed Plan:
  ${rawPlan}
  
  Critique this plan. What are the hidden risks? What happens if the market crashes? Is the risk appetite too high/low for their goals? Provide 3 sharp, critical bullet points. (Markdown format)`;

  const response = await withRetry(() => getOrchestratorAI().models.generateContent({
    model: GEMINI_MODELS.DEFAULT,
    contents: prompt
  }), onRetry);
  return response.text || 'Challenge failed to generate.';
};
